const data = [
    {
        lesson: 1, 
        title_en: "A puma at large",
        title_cn: "逃遁的美洲狮", 
        content: "Pumas are large, cat-like animals which are found in America. When reports came into London Zoo that a wild puma had been spotted forty-five miles south of London, they were not taken seriously. However, as the evidence began to accumulate, experts from the Zoo felt obliged to investigate, for the descriptions given by people who claimed to have seen the puma were extraordinarily similar. The hunt for the puma began in a small village where a woman picking blackberries saw 'a large cat' only five yards away from her. It immediately ran away when she saw it, and experts confirmed that a puma will not attack a human being unless it is cornered. The search proved difficult, for the puma was often observed at one place in the morning and at another place twenty miles away in the evening. Wherever it went, it left behind it a trail of dead deer and small animals like rabbits. Paw prints were seen in a number of places and puma fur was found clinging to bushes. Several people complained of 'cat-like noises' at night and a businessman on a fishing trip saw the puma up a tree. The experts were now fully convinced that the animal was a puma, but where had it come from? As no pumas had been reported missing from any zoo in the country, this one must have been in the possession of a private collector and somehow managed to escape. The hunt went on for several weeks, but the puma was not caught. It is disturbing to think that a dangerous wild animal is still at large in the quiet countryside.",
        translation: "美洲狮是一种体形似猫的大动物，产于美洲。当伦敦动物园接到报告说，在伦敦以南45英里处发现一只美洲狮时，这些报告并没有受到重视。可是，随着证据越来越多，动物园的专家们感到有必要进行一番调查，因为凡是声称见到过美洲狮的人们所描述的情况竟是出奇地相似。搜寻美洲狮的工作是从一座小村庄开始的。那里的一位妇女在采摘黑莓时的看见“一只大猫”，离她仅5码远，她刚看见它，它就立刻逃走了。专家证实，美洲狮非被逼得走投无路，是决不会伤人的。事实上搜寻工作很困难，因为常常是早晨在甲地发现那只美洲狮，晚上却在20英里外的乙地发现它的踪迹。无论它走哪儿，一路上总会留下一串死鹿及死兔子之类的小动物，在许多地方看见爪印，灌木丛中发现了粘在上面的美洲狮毛。有人抱怨说夜里听见“像猫一样的叫声”；一位商人去钓鱼，看见那只美洲狮在树上。专家们如今已经完全肯定那只动物就是美洲狮，但它是从哪儿来的呢？由于全国动物园没有一家报告丢了美洲狮，因此那只美洲狮一定是某位私人收藏豢养的，不知怎么设法逃出来了。搜寻工作进行了好几个星期，但始终未能逮住那只美洲狮。想到在宁静的乡村里有一头危险的野兽继续逍遥流窜，真令人担心。",
        audio_uk: "https://i.xiao84.com/en-nce/3mp3-en/Lesson 01.mp3",
        audio_us: "https://i.xiao84.com//en-nce/3mp3-us/III-01.mp3",
    },

    {
        lesson: 41, 
        title_en: "Illusions of pastoral peace",
        title_cn: "宁静田园生活的遐想", 
        content: "The quiet life of the country has never appealed to me. City born and city bred, I have always regarded the country as something you look at through a train window, or something you occasionally visit during the weekend. Most of my friends live in the city, yet they always go into raptures at the mere mention of the country. Though they extol the virtues of the peaceful life, only one of them has ever gone to live in the country and he was back in town within six months. Even he still lives under the illusion that country life is somehow superior to town life. He is forever talking about the friendly people, the clean atmosphere, the closeness to nature and the gentle pace of living. Nothing can be compared, he maintains, with the first cockcrow, the twittering of birds at dawn, the sight of the rising sun glinting on the trees and pastures. This idyllic pastoral scene is only part of the picture. My friend fails to mention the long and friendless winter evenings in front of the TV ---- virtually the only form of entertainment. He says nothing about the poor selection of goods in the shops, or about those unfortunate people who have to travel from the country to the city every day to get to work. Why people are prepared to tolerate a four-hour journey each day for the dubious privilege of living in the country is beyond me. They could be saved so much misery and expense if they chose to live in the city where they rightly belong. If you can do without the few pastoral pleasures of the country, you will find the city can provide you with the best that life can offer. You never have to travel miles to see your friends. They invariably live nearby and are always available for an informal chat or an evening's entertainment. Some of my acquaintances in the country come up to town once or twice a year to visit the theatre as a special treat. For them this is a major operation which involves considerable planning. As the play draws to its close, they wonder whether they will ever catch that last train home. The city dweller never experiences anxieties of this sort. The latest exhibitions, films, or plays are only a short bus ride away. Shopping, too, is always a pleasure. There is so much variety that you never have to make do with second best. Country people run wild when they go shopping in the city and stagger home loaded with as many of the exotic items as they can carry. Nor is the city without its moments of beauty. There is something comforting about the warm glow shed by advertisements on cold wet winter nights. Few things could be more impressive than the peace that descends on deserted city streets at weekends when the thousands that travel to work every day are tucked away in their homes in the country. It has always been a mystery to me why city dwellers, who appreciate all these things, obstinately pretend that they would prefer to live in the country.",
        translation: "宁静的乡村生活从来没有吸引过我。我生在城市，长在城市，总认为乡村是透过火车车窗看到的那个样子，或偶尔周末去游玩一下的景象。我的许多朋友都住在城市，但他们只要一提起乡村，马上就会变得欣喜若狂。尽管他们都交口称赞宁静的乡村生活的种种优点，但其中只有一人真去农村住过，而且不足6个月就回来了。即使他也仍存有幻觉，好像乡村生活就是比城市生活优越。他滔滔不绝地大谈友好的农民，洁净的空气，贴近大自然的环境和悠闲的生活节奏。他坚持认为，凌晨雄鸡第一声啼叫，黎明时分小鸟吱喳欢叫，冉冉升起的朝阳染红树木、牧场，此番美景无与伦比。但这种田园诗般的乡村风光仅仅是一个侧面。我的朋友没有提到在电视机前度过的漫长寂寞的冬夜——电视是唯一的娱乐形式。他也不说商店货物品种单调，以及那些每天不得不从乡下赶到城里工作的不幸的人们。人们为什么情愿每天在路上奔波4个小时去换取值得怀疑的乡间的优点，我是无法理解的。要是他们愿意住在本来属于他们的城市，则可以让他们省去诸多不便与节约大量开支。如果你愿舍弃乡下生活那一点点乐趣的话，那么你会发现城市可以为你提供生活中最美好的东西。你去看朋友根本不用跋涉好几英里，因为他们都住在附近，你随时可以同他们聊天或在晚上一起娱乐。我在乡村有一些熟人，他们每年进城来看一回或几回戏，并把此看作一种特殊的享受。看戏在他们是件大事，需要精心计划。当戏快演完时，他们又为是否能赶上末班火车回家而犯愁。这种焦虑，城里人是从未体验过的。坐公共汽车几站路，就可看到最新的展览、电影、戏剧。买东西也是一种乐趣。物品品种繁多，从来不必用二等品来凑合。乡里人进城采购欣喜若狂，每次回家时都买足了外来商品，直到拿不动方才罢休，连走路都摇摇晃晃的。城市也并非没有良辰美景。寒冷潮湿的冬夜里，广告灯箱发出的暖光，会给人某种安慰。周末，当成千上万进城上班的人回到了他们的乡间寓所之后，空旷的街市笼罩着一种宁静的气氛，没有什么能比此时的宁静更令人难忘了。城里人对这一切心里很明白，却偏要执拗地装出他们喜欢住在乡村的样子，这对我来说一直是个谜。",
        audio_uk: "https://i.xiao84.com/en-nce/3mp3-en/Lesson 41.mp3",
        audio_us: "https://i.xiao84.com//en-nce/3mp3-us/III-41.mp3",
    }
]
